INSERT INTO DISTRICT(ID, NAME, CODE) VALUES (1, 'ANKARA', -1);
INSERT INTO DISTRICT(ID, NAME, CODE) VALUES (2, 'ANKARA', 1);
INSERT INTO DISTRICT(ID, NAME, CODE) VALUES (3, 'ANKARA', 1);
INSERT INTO DISTRICT(ID, NAME, CODE) VALUES (4, 'ANKARA', 1);
